import Head from "next/head";
import styled from "styled-components/macro";
import tw from "twin.macro";
import Hero from "../components/Hero";
import About from "../components/About";
import Navbar from "../components/Navbar";
import Discover from "../components/Discover";
import Signup from "../components/Signup";
import Services from "../components/Services";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Home - dolla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Discover />
      <Services />
      <Signup />
      <Footer />
    </Container>
  );
}

const Container = styled.div`
  scroll-behavior: smooth;
`;

const H1 = styled.h1`
  ${tw`font-bold text-3xl`}
`;
