import Head from "next/head";
import styled from "styled-components/macro";
import tw from "twin.macro";
import Brand from "../components/Brand";
import Navbar from "../components/Navbar";
import SigninForm from "../components/SigninForm";

const signin = ({ ...props }) => {
  return (
    <>
      <Head>
        <title>Sign in - dolla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {/* <Navbar /> */}
        <BrandWrapper>
          <Brand />
        </BrandWrapper>
        <FormWrapper>
          <SigninForm />
        </FormWrapper>
      </Container>
    </>
  );
};

const Container = styled.div`
  ${tw`flex flex-col h-screen bg-green-500`}
`;

const BrandWrapper = styled.div`
  ${tw`mx-auto p-6`}
`;

const FormWrapper = styled.div`
  ${tw`flex flex-1 justify-center items-center`}
`;

export default signin;
